# Production Configuration for Rave Web Services Mock API
# This file contains runtime configuration for production/development use

# Server Configuration
server:
  port: 3000
  host: "0.0.0.0"
  bodyLimit: 10485760  # 10MB

# RWS Version
rws:
  version: "1.8.0"

# Authentication Configuration
auth:
  # In production, these would come from environment variables or secrets management
  basic_auth:
    enabled: true
    # Users should be managed externally
    allow_any_credentials: true  # For mock purposes
  
  mauth:
    enabled: true
    # In production, this would verify actual MAuth signatures
    stub_mode: true

# ODM Configuration
odm:
  namespace:
    odm: "http://www.cdisc.org/ns/odm/v1.3"
    mdsol: "http://www.mdsol.com/ns/odm/metadata"
  
  version: "1.3"
  
  default_file_type: "Snapshot"
  
  # Default Study Metadata Structure
  default_study:
    study_name: "Mock Study"
    study_description: "Mock study metadata"
    protocol_name: "MOCK-001"
  
  # Default Study Events (can be overridden per study)
  study_events:
    - oid: "SCREENING"
      name: "Screening"
      type: "Scheduled"
      repeating: false
      order: 1
    
    - oid: "BASELINE"
      name: "Baseline"
      type: "Scheduled"
      repeating: false
      order: 2
    
    - oid: "FOLLOWUP"
      name: "Follow-up"
      type: "Scheduled"
      repeating: true
      order: 3
  
  # Default Forms
  forms:
    - oid: "DM"
      name: "Demographics"
      repeating: false
      item_group: "DM_IG"
    
    - oid: "AE"
      name: "Adverse Events"
      repeating: true
      item_group: "AE_IG"
    
    - oid: "VS"
      name: "Vital Signs"
      repeating: true
      item_group: "VS_IG"
  
  # Default Item Groups
  item_groups:
    - oid: "DM_IG"
      name: "Demographics"
      repeating: false
      items:
        - "SUBJID"
        - "AGE"
        - "SEX"
        - "RACE"
    
    - oid: "AE_IG"
      name: "Adverse Events"
      repeating: true
      items:
        - "AETERM"
        - "AESEV"
        - "AEDATE"
    
    - oid: "VS_IG"
      name: "Vital Signs"
      repeating: true
      items:
        - "VSDTC"
        - "SYSBP"
        - "DIABP"
        - "PULSE"
        - "TEMP"
  
  # Default Item Definitions
  items:
    - oid: "SUBJID"
      name: "Subject ID"
      data_type: "text"
      question: "Subject ID"
      mandatory: true
    
    - oid: "AGE"
      name: "Age"
      data_type: "integer"
      question: "Age"
      mandatory: false
    
    - oid: "SEX"
      name: "Sex"
      data_type: "text"
      question: "Sex"
      mandatory: false
    
    - oid: "RACE"
      name: "Race"
      data_type: "text"
      question: "Race"
      mandatory: false
    
    - oid: "SYSBP"
      name: "Systolic Blood Pressure"
      data_type: "integer"
      question: "Systolic BP"
      mandatory: false
    
    - oid: "DIABP"
      name: "Diastolic Blood Pressure"
      data_type: "integer"
      question: "Diastolic BP"
      mandatory: false
    
    - oid: "PULSE"
      name: "Pulse"
      data_type: "integer"
      question: "Pulse"
      mandatory: false
    
    - oid: "TEMP"
      name: "Temperature"
      data_type: "float"
      question: "Temperature"
      mandatory: false
    
    - oid: "AETERM"
      name: "Adverse Event Term"
      data_type: "text"
      question: "AE Term"
      mandatory: true
    
    - oid: "AESEV"
      name: "Severity"
      data_type: "text"
      question: "Severity"
      mandatory: false
    
    - oid: "AEDATE"
      name: "AE Start Date"
      data_type: "date"
      question: "Start Date"
      mandatory: false
    
    - oid: "VSDTC"
      name: "Visit Date"
      data_type: "datetime"
      question: "Visit Date/Time"
      mandatory: false

# CSV Dataset Headers
csv_datasets:
  Users:
    - "UserOID"
    - "Username"
    - "FirstName"
    - "LastName"
    - "Email"
    - "Active"
    - "Role"
  
  Sites:
    - "StudyOID"
    - "SiteNumber"
    - "SiteName"
    - "SiteStatus"
    - "Country"
    - "Investigator"
  
  Signatures:
    - "StudyOID"
    - "SiteNumber"
    - "SubjectName"
    - "FormOID"
    - "SignatureDate"
    - "Username"
  
  VersionFolders:
    - "StudyOID"
    - "FolderOID"
    - "FolderName"
    - "VersionNumber"
    - "Primary"
  
  ClinicalView:
    - "StudyOID"
    - "SiteNumber"
    - "SubjectName"
    - "FieldOID"
    - "FieldValue"
    - "RecordDate"

# Response Configuration
responses:
  success:
    reference_number_default: "0000"
    inbound_file_oid: "mockFile"
    is_transaction_successful: "1"
  
  error:
    reference_number: "error"
    is_transaction_successful: "0"
  
  # RWS Error Codes
  error_codes:
    RWS00001:
      message: "Required parameter missing"
      http_status: 400
    
    RWS00002:
      message: "Invalid parameter value"
      http_status: 400
    
    RWS00003:
      message: "Invalid ODM XML structure"
      http_status: 400
    
    RWS00004:
      message: "Missing required ODM attributes"
      http_status: 400
    
    RWS00092:
      message: "CRF version not found"
      http_status: 404
    
    RWS00401:
      message: "Authentication required"
      http_status: 401
    
    RWS00403:
      message: "Access denied"
      http_status: 403

# Pagination
pagination:
  default_per_page: 100
  max_per_page: 1000

# Cache Configuration
cache:
  enabled: true
  flush_response:
    status: "cache flushed"

# Logging
logging:
  level: "info"
  pretty: true
  test_mode: false

# Features
features:
  # Return empty datasets as per specification
  empty_datasets: true
  
  # Support pagination
  pagination: true
  
  # Validate ODM structure
  validate_odm: true

