# Test Configuration for Rave Web Services Mock API
# This file contains all mock data and configuration used in tests

# Server Configuration
server:
  port: 3000
  host: "0.0.0.0"
  bodyLimit: 10485760  # 10MB

# RWS Version
rws:
  version: "1.8.0"

# Authentication Test Data
auth:
  test_credentials:
    - username: "test"
      password: "test123"
    - username: "testuser"
      password: "testpass"
    - username: "admin"
      password: "admin123"
  
  mauth:
    enabled: true
    test_signature: "mock-signature"

# ODM Configuration
odm:
  namespace:
    odm: "http://www.cdisc.org/ns/odm/v1.3"
    mdsol: "http://www.mdsol.com/ns/odm/metadata"
  
  version: "1.3"
  
  default_file_type: "Snapshot"
  
  # Test Study Configuration
  test_studies:
    - study_oid: "STUDY001"
      study_name: "Mock Study 001"
      study_description: "Mock study metadata for testing"
      protocol_name: "MOCK-001"
    
    - study_oid: "STUDY123"
      study_name: "Mock Study 123"
      study_description: "Mock study metadata for testing"
      protocol_name: "MOCK-123"
    
    - study_oid: "PROTOCOL001"
      study_name: "Protocol Study 001"
      study_description: "Protocol study for clinical data import"
      protocol_name: "PROTOCOL-001"
  
  # Default Study Metadata Structure
  default_study:
    study_name: "Mock Study"
    study_description: "Mock study metadata"
    protocol_name: "MOCK-001"
  
  # Study Events
  study_events:
    - oid: "SCREENING"
      name: "Screening"
      type: "Scheduled"
      repeating: false
      order: 1
    
    - oid: "VISIT1"
      name: "Visit 1"
      type: "Scheduled"
      repeating: false
      order: 2
  
  # Forms
  forms:
    - oid: "DM"
      name: "Demographics"
      repeating: false
      item_group: "DM_IG"
    
    - oid: "DEMOGRAPHICS"
      name: "Demographics"
      repeating: false
      item_group: "DM_GROUP"
    
    - oid: "VITALS"
      name: "Vital Signs"
      repeating: false
      item_group: "VS_GROUP"
  
  # Item Groups
  item_groups:
    - oid: "DM_IG"
      name: "Demographics"
      repeating: false
      items:
        - "SUBJID"
        - "AGE"
    
    - oid: "DM_GROUP"
      name: "Demographics Group"
      repeating: false
      items:
        - "SUBJID"
        - "AGE"
        - "SEX"
        - "RACE"
    
    - oid: "VS_GROUP"
      name: "Vital Signs Group"
      repeating: false
      items:
        - "SYSBP"
        - "DIABP"
        - "PULSE"
        - "TEMP"
  
  # Item Definitions
  items:
    - oid: "SUBJID"
      name: "Subject ID"
      data_type: "text"
      question: "Subject ID"
      mandatory: true
    
    - oid: "AGE"
      name: "Age"
      data_type: "integer"
      question: "Age"
      mandatory: false
    
    - oid: "SEX"
      name: "Sex"
      data_type: "text"
      question: "Sex"
      mandatory: false
    
    - oid: "RACE"
      name: "Race"
      data_type: "text"
      question: "Race"
      mandatory: false
    
    - oid: "SYSBP"
      name: "Systolic Blood Pressure"
      data_type: "integer"
      question: "Systolic BP"
      mandatory: false
    
    - oid: "DIABP"
      name: "Diastolic Blood Pressure"
      data_type: "integer"
      question: "Diastolic BP"
      mandatory: false
    
    - oid: "PULSE"
      name: "Pulse"
      data_type: "integer"
      question: "Pulse"
      mandatory: false
    
    - oid: "TEMP"
      name: "Temperature"
      data_type: "float"
      question: "Temperature"
      mandatory: false
  
  # Test Subjects
  test_subjects:
    - subject_key: "001"
      subject_name: "SUBJ-001"
      age: 45
      sex: "M"
      race: "Caucasian"
    
    - subject_key: "002"
      subject_name: "SUBJ-002"
      age: 32
      sex: "F"
      race: "Asian"

# CSV Dataset Headers
csv_datasets:
  Users:
    - "UserOID"
    - "Username"
    - "FirstName"
    - "LastName"
    - "Email"
    - "Active"
    - "Role"
  
  Sites:
    - "StudyOID"
    - "SiteNumber"
    - "SiteName"
    - "SiteStatus"
    - "Country"
    - "Investigator"
  
  Signatures:
    - "StudyOID"
    - "SiteNumber"
    - "SubjectName"
    - "FormOID"
    - "SignatureDate"
    - "Username"
  
  VersionFolders:
    - "StudyOID"
    - "FolderOID"
    - "FolderName"
    - "VersionNumber"
    - "Primary"
  
  ClinicalView:
    - "StudyOID"
    - "SiteNumber"
    - "SubjectName"
    - "FieldOID"
    - "FieldValue"
    - "RecordDate"

# Response Configuration
responses:
  success:
    reference_number_default: "0000"
    inbound_file_oid: "mockFile"
    is_transaction_successful: "1"
  
  error:
    reference_number: "error"
    is_transaction_successful: "0"
  
  # RWS Error Codes
  error_codes:
    RWS00001:
      message: "studyoid parameter is required"
      http_status: 400
    
    RWS00003:
      message: "Invalid ODM XML. Must contain <ODM> root element"
      http_status: 400
    
    RWS00004:
      message: "ODM XML must include ODMVersion and FileType attributes"
      http_status: 400
    
    RWS00092:
      message: "CRF version not found"
      http_status: 404

# Test Scenarios
test_scenarios:
  # Valid ODM Import
  valid_odm_import:
    study_oid: "STUDY001"
    file_type: "Transactional"
    file_oid: "import-001"
    creation_date_time: "2024-01-01T00:00:00"
    subjects:
      - subject_key: "001"
        study_event: "SCREENING"
        form: "DM"
        item_group: "DM_IG"
        items:
          SUBJID: "001"
  
  # Invalid ODM samples
  invalid_odm_samples:
    - name: "Missing ODM root"
      xml: "<Invalid>XML</Invalid>"
      expected_error: "Invalid ODM XML"
    
    - name: "Missing required attributes"
      xml: "<ODM><ClinicalData/></ODM>"
      expected_error: "ODMVersion"
  
  # Pagination test
  pagination:
    default_per_page: 100
    test_start_id: 1000
    test_study_oid: "STUDY001"

# Cache Configuration
cache:
  flush_response:
    status: "cache flushed"

# Logging
logging:
  level: "info"
  pretty: true
  test_mode: false

